//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActionBarDemo
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int title = 2130771968;
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040003
			public const int actionbar_background_end = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int actionbar_background_item_pressed_end = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int actionbar_background_item_pressed_start = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int actionbar_background_start = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int actionbar_separator = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int actionbar_title = 2130968577;
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int actionbar_height = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int actionbar_item_height = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int actionbar_item_width = 2131034114;
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int actionbar_back_indicator = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int actionbar_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int actionbar_btn = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int actionbar_btn_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int actionbar_btn_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_back = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_action_message = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08000c
			public const int actionbar = 2131230732;
			
			// aapt resource value: 0x7f080009
			public const int actionbar_actions = 2131230729;
			
			// aapt resource value: 0x7f080001
			public const int actionbar_home = 2131230721;
			
			// aapt resource value: 0x7f080006
			public const int actionbar_home_bg = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int actionbar_home_btn = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int actionbar_home_is_back = 2131230728;
			
			// aapt resource value: 0x7f080004
			public const int actionbar_home_logo = 2131230724;
			
			// aapt resource value: 0x7f08000b
			public const int actionbar_item = 2131230731;
			
			// aapt resource value: 0x7f080003
			public const int actionbar_left_actions = 2131230723;
			
			// aapt resource value: 0x7f08000a
			public const int actionbar_progress = 2131230730;
			
			// aapt resource value: 0x7f080005
			public const int actionbar_title = 2131230725;
			
			// aapt resource value: 0x7f080002
			public const int linearLayout1 = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int screen = 2131230720;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int actionbar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int actionbar_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int actionbar_activity_not_found = 2131099650;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int ActionBar = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int ActionBarHomeItem = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int ActionBarHomeLogo = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int ActionBarItem = 2131165185;
			
			// aapt resource value: 0x7f070004
			public const int ActionBarProgressBar = 2131165188;
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ActionBar = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int ActionBar_title = 0;
			
			private Styleable()
			{
			}
		}
	}
}
